### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by TimLeeCV** [zjuzhk/MCNet#2]
Hello author, I would like to ask if the test set of this article is a subset generated in the COCO test set? Or use the entire COCO test set.

**Comment by zjuzhk** [comment]
It should be the entire COCO test set. For more details about test, please refer to the appendix, thks!

**Comment by TimLeeCV** [comment]
> It should be the entire COCO test set. For more details about test, please refer to the appendix, thks!

Thanks for your reply！
